name: zizmor

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"

jobs:
  zizmor:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    permissions:
      contents: read

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
        with:
          inputs: "."
          min-severity: low
          min-confidence: low
          version: 1.23.1 # zizmor maintains a static map of version hashes so this is actually pinned https://github.com/zizmorcore/zizmor-action/blob/main/support/versions
          advanced-security: false # print to console instead of uploading a SARIF
          fail-on-no-inputs: true
